// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpupdxvbgzzvyxcmtnhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwdXBkeHZiZ3p6dnl4Y210bmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDgxODAsImV4cCI6MjA2ODgyNDE4MH0.yvWldPjIZvuy6I3jvAuN045b6EYHK4HI8SjXtZg4plY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});